alpha: 0.1
distill_loss: "all"
n_low: 2
batch_size: 128
epochs: 50
output_dir: "./train_results/"
device: "cuda"
seed: 0
resume: ""
start_epoch: 0
num_workers: 64
pin_mem: true
no_pin_mem: false
world_size: 1
dist_url: "env://"
dist_eval: false
distillation_type: "soft"
distillation_tau: 1.0
distillation_alpha: 0.5
blk_length: 9
ls_init: true
init_learngenepool_mode: ours
init_stitch_mode: "snnet"
learngenepool_ckpt: "instance_ours"
stitch_init_bs: 100
eval: true
cfg_id: 2
sched: "cosine"
lr: 1e-4
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
warmup_lr: 1e-6
min_lr: 1e-5
decay_epochs: 30
warmup_epochs: 5
cooldown_epochs: 10
patience_epochs: 10
decay_rate: 0.1
teacher_model: "deit_base_patch16_224"
student_model: "deit_base3_patch16_224"
patch_size: 16
num_heads: 3
head_dim: 64
num_blocks: 12
throughput: false
drop: 0.0
drop_path: 0.1
model_ema: true
no_model_ema: false
model_ema_decay: 0.99996
model_ema_force_cpu: false
stitch_id: [2, 2, 2]
temperature: 1.0
loss_pos: "[front,end]"
input_size: 224
data_path: "/home/shiboyu/dataset/ILSVRC2012"
data_set: "IMNET"
opt: "adamw"
opt_eps: 1e-8
opt_betas: null
clip_grad: null
momentum: 0.9
weight_decay: 0.05
color_jitter: 0.4
aa: "rand-m9-mstd0.5-inc1"
smoothing: 0.1
train_interpolation: "bicubic"
repeated_aug: true
no_repeated_aug: false
reprob: 0.25
remode: "pixel"
recount: 1
resplit: false
mixup: 0.8
cutmix: 1.0
cutmix_minmax: null
mixup_prob: 1.0
mixup_switch_prob: 0.5
mixup_mode: "batch"
