#!/usr/bin/env python
# -*- coding:utf-8 -*-


batch_size: 128
epochs: 40
unscale_lr: true

model: model-type
pretrained: false
input_size: 224

drop: 0.0
drop_path: 0.1

model_ema: true
model_ema_decay: 0.99996
model_ema_force_cpu: false

opt: adamw
opt_eps: !!float 1e-8
opt_betas: null
clip_grad: null
accumulation_step: 1
momentum: 0.9
weight_decay: 0.05

sched: cosine
lr: !!float 5e-4
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
warmup_lr: !!float 1e-6
min_lr: !!float 1e-5

decay_epochs: 30
warmup_epochs: 0
cooldown_epochs: 10
patience_epochs: 10
decay_rate: 0.1

color_jitter: 0.4
aa: rand-m9-mstd0.5-inc1
smoothing: 0.1
train_interpolation: bicubic

repeated_aug: true
load_tar: true
train_mode: true

reprob: 0.25
remode: pixel
recount: 1
resplit: false

mixup: 0.8
cutmix: 1.0
cutmix_minmax: null
mixup_prob: 1.0
mixup_switch_prob: 0.5
mixup_mode: batch

teacher_model: regnety_160
teacher_path:
distillation_type: none
distillation_alpha: 0.5
distillation_tau: 1.0

finetune:

data_path: /path/to/imagenet
data_set: IMNET
inat_category: name

output_dir: /path/to/save
device: cuda
seed: 123
resume:
load_gene: /path/to/base_learngene
start_epoch: 0
eval: false
eval_crop_ratio: 0.875
dist_eval: true

num_workers: 0
pin_mem: true

world_size: 1
dist_url: env://