METHOD_FAMILY: 'heur_vgg'
OUTPUT_DIR: './outputs/heur_vgg/ancestor_model'
SEED: 1
DEVICE: 'cuda'

DATASET:
  NAME: 'cifar100'
  # !!! 注意: 请将 PATH 修改为您自己的 continualdataset 路径 !!!
  PATH: 'D:/stu_res/reconstruct/YuanMou/learngene/datasets/exp_data/data_cifar100/2023-12-08_07_41_26/continualdataset'
  NUM_WORKS: 21

MODEL:
  TYPE: 'netwider'
  BASE_LAYERS: 13

TRAIN:
  EPOCHS: 100
  BATCH_SIZE: 16
  LR: 0.01
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-4
  LR_DROP: 0.4
  EPOCHS_DROP: 100