METHOD_FAMILY: 'tleg_vit'
OUTPUT_DIR: './outputs/tleg_vit/ancestor_aux_tiny'
SEED: 123
DEVICE: 'cuda'

DATASET:
  NAME: 'CIFAR100' # 'IMNET', 'CIFAR10', etc.
  # !!! 注意: 请将 PATH 修改为您自己的数据集路径 !!!
  PATH: '/path/to/cifar100'
  INPUT_SIZE: 224
  PIN_MEM: True
  NUM_WORKERS: 4

MODEL:
  TYPE: 'aux_deit_tiny_patch16_224' # 祖先模型类型
  PRETRAINED: True
  DROP: 0.0
  DROP_PATH: 0.1
  EMA: True
  EMA_DECAY: 0.99996

TRAIN:
  EPOCHS: 300
  START_EPOCH: 0
  BATCH_SIZE: 128
  UNSCALE_LR: False # 如果为True，则不根据batch size缩放学习率

  # 优化器
  OPT: 'adamw'
  OPT_EPS: 1e-8
  WEIGHT_DECAY: 0.05
  MOMENTUM: 0.9
  
  # 学习率调度器
  SCHED: 'cosine'
  LR: 0.0005 # 基础学习率，如果 UNSCALE_LR 为 False，会被自动缩放
  WARMUP_EPOCHS: 5
  WARMUP_LR: 1e-6
  MIN_LR: 1e-5

  # Augmentation 和 Loss
  SMOOTHING: 0.1
  MIXUP: 0.8
  CUTMIX: 1.0
  COLOR_JITTER: 0.4
  AA: 'rand-m9-mstd0.5-inc1'
  REPROB: 0.25

# 分布式训练配置
DISTRIBUTED:
  WORLD_SIZE: 1
  DIST_URL: 'env://'
  DIST_EVAL: True