METHOD_FAMILY: 'tleg_vit'
OUTPUT_DIR: './outputs/tleg_vit/descendant_deit_tiny_L6'
SEED: 123
DEVICE: 'cuda'

DATASET:
  NAME: 'CIFAR100'
  PATH: '/path/to/cifar100' # 与祖先模型使用相同的数据集
  INPUT_SIZE: 224
  PIN_MEM: True
  NUM_WORKERS: 4

MODEL:
  # 选择一个后代模型类型
  TYPE: 'deit_tiny_patch16_224_L6' 
  # !!! 注意: LOAD_GENE 应指向祖先模型训练输出的 checkpoint.pth 文件 !!!
  LOAD_GENE: './outputs/tleg_vit/ancestor_aux_tiny/checkpoint.pth'
  DROP: 0.0
  DROP_PATH: 0.1
  EMA: True
  EMA_DECAY: 0.99996

TRAIN:
  # ... 训练参数与祖先模型类似，但可以调整 ...
  EPOCHS: 300
  START_EPOCH: 0
  BATCH_SIZE: 128
  UNSCALE_LR: False
  OPT: 'adamw'
  LR: 0.0005
  WARMUP_EPOCHS: 5
  # ... 其他参数 ...

# ... 分布式配置 ...